/* Definitions, symptoms and RUF acquisition education. No diagnostic calculations. */
const CONDITIONS=DATA.conditions, CLINICAL_SOURCES=DATA.clinicalSources;
const GROWTH_URL='https://growthai-two.vercel.app/';
const RUF=[
 {id:'ulna',name:'척골 원위부',short:'척골',prefix:'U',panel:'B',position:'편하게 눕거나 앉아 왼쪽 전완을 받칩니다. 전완을 회내하여 손등이 위로 향하게 하고, 새끼손가락 쪽 손목을 노출합니다.',landmark:'새끼손가락 쪽 척골경상돌기와 원위 척골 골피질을 찾습니다. 손목터널이나 ECU 건 자체가 촬영 목표는 아닙니다.',probe:'고주파 선형 탐촉자를 척골 원위부의 척측에 뼈 길이 방향으로 놓습니다. 경상돌기 쪽에서 관상면을 기준으로 조금씩 돌리고 기울여 골단의 전체 윤곽이 가장 잘 보이는 단면을 찾습니다.',find:'골간단의 밝은 피질선, 그 원위부의 저에코 연골성 골단, 내부 골화중심의 경계가 한 화면에 들어오게 합니다. 연골의 바깥 경계를 잘라내지 않습니다.',pitfall:'ECU 건이나 척골경상돌기만 보고 저장하지 않습니다. 어린 연령에서는 골화중심이 작거나 뚜렷하지 않을 수 있으므로 억지로 표시하거나 다른 고에코 구조를 골화중심으로 선택하지 않습니다.',ref:'손등 ↑ · 새끼손가락 쪽 · 뼈 길이 방향'},
 {id:'radius',name:'요골 원위부',short:'요골',prefix:'R',panel:'A',position:'같은 쪽 전완을 받치고 손목을 편안한 중립 위치로 둡니다. 엄지 쪽 면에 탐촉자를 놓을 수 있도록 손과 전완을 함께 조정합니다.',landmark:'엄지 쪽 요골경상돌기와 원위 요골 피질을 찾습니다. 표적은 수근골이 아니라 원위 요골의 골단입니다.',probe:'엄지 쪽 원위 요골에 탐촉자를 뼈 길이 방향으로 놓고 관상면을 기준으로 맞춥니다. 작은 이동·회전으로 비스듬히 잘린 단면을 피하고 골단과 골화중심의 경계를 확보합니다.',find:'원위 요골 골간단과 연골성 골단·골화중심의 윤곽을 함께 보이게 합니다. 척골 촬영과 같은 영상 방향 규칙을 유지합니다.',pitfall:'손목 등쪽 성인 MSK 검사 단면을 그대로 대신 쓰지 않습니다. 문헌마다 단면 명칭에 차이가 있어 표준 사진·표적 윤곽을 함께 확인하며 추적 검사에서는 동일한 촬영법을 유지합니다.',ref:'전완 중립 · 엄지 쪽 · 뼈 길이 방향'},
 {id:'femur',name:'대퇴골 원위부',short:'대퇴골',prefix:'F',panel:'C',position:'바로 누운 자세에서 왼쪽 무릎 아래에 받침을 대어 가볍게 굽히고, 무릎 안쪽에 접근하도록 다리를 편안하게 벌립니다. 자세는 통증 없이 유지합니다.',landmark:'무릎 안쪽의 원위 대퇴골 내측상과·내측과 부위를 찾습니다. 슬개골, 경골 근위부, 경골조면과 혼동하지 않습니다.',probe:'탐촉자를 원위 대퇴골 내측의 관상면에 뼈 길이 방향으로 놓습니다. 내측측부인대를 기준점으로 주변을 천천히 훑고, 필요하면 그 뒤쪽에서 골단과 골화중심을 잘 드러내는 단면을 찾습니다.',find:'원위 대퇴골 골간단 피질과 연골성 골단, 골화중심이 함께 보이도록 깊이·초점을 조정합니다. 손목보다 표적이 깊을 수 있어 같은 깊이 설정을 그대로 적용하지 않습니다.',pitfall:'내측측부인대 장축이나 관절간격만 선명하다고 저장하지 않습니다. 무릎 굽힘·회전이 달라지면 단면도 바뀌므로 재촬영마다 자세를 다시 확인합니다.',ref:'바로 누움 · 무릎 약간 굽힘 · 무릎 안쪽'}
];
const clinicalDialog=document.createElement('dialog');clinicalDialog.className='clinical-dialog';clinicalDialog.setAttribute('aria-labelledby','clinical-title');document.body.append(clinicalDialog);
function diseaseButtons(id,i){let rows=CONDITIONS[id][i].conditions;return `<section class="disease-entry" aria-label="관련 질환 정의와 증상"><div><span class="eyebrow">CLINICAL CONTEXT</span><h2>어떤 질환인가요?</h2><p>정의와 대표 증상을 먼저 연결해 보세요.</p></div><div class="disease-buttons">${rows.map((c,j)=>`<button data-condition="${id}/${i}/${j}"><span>${e(c.name)}</span><small>정의 · 증상 보기 <b>＋</b></small></button>`).join('')}</div></section>`}
function showCondition(id,i,j){const c=CONDITIONS[id]?.[i]?.conditions[j];if(!c)return;let source=CLINICAL_SOURCES[c.source];clinicalDialog.innerHTML=`<div class="dialog-toolbar"><span class="eyebrow">${names[id]} · ${i+1}단계</span><button data-clinical-close aria-label="질환 설명 닫기">닫기 ✕</button></div><div class="clinical-body"><h2 id="clinical-title">${e(c.name)}</h2><section class="definition-box"><span class="clinical-number">01</span><div><h3>정의 · 무엇이 달라진 상태인가요?</h3><p>${e(c.definition)}</p></div></section><section class="symptom-box"><h3>02 · 대표 증상</h3><ul>${c.symptoms.split(';').map(t=>`<li>${e(t)}</li>`).join('')}</ul><p class="small muted">증상은 사람마다 다르며, 같은 증상이 다른 질환에서도 나타날 수 있습니다.</p></section><section class="clinical-link"><h3>03 · 초음파와 연결해서 보기</h3><p>${e(c.link)}</p><small>현재 검사 영역: ${e(P[id].steps[i].education.name)}</small></section><div class="source-links"><a href="${source[1]}" target="_blank" rel="noopener noreferrer">${e(source[0])} ↗</a></div><div class="actions"><button class="primary" data-clinical-close>검사 화면으로 돌아가기</button></div>${footer()}</div>`;clinicalDialog.showModal()}
function growthLink(){return `<a class="button growth-external" href="${GROWTH_URL}" target="_blank" rel="noopener noreferrer">Growth AI 성장판독보조로 이동 ↗</a>`}
function rufRail(i=-1){return `<nav class="ruf-rail" aria-label="RUF 촬영 순서">${RUF.map((r,j)=>`<a href="#ruf/${j+1}" ${i===j?'aria-current="step"':''}><b>0${j+1}</b><span>${r.name}<small>${r.prefix}01 · ${r.prefix}02 · ${r.prefix}03</small></span><strong>3장</strong></a>`).join('')}</nav>`}
function rufSources(){return `<details class="ruf-source"><summary>RUF 근거·촬영안 구분 및 사진 출처</summary><div class="details-body"><p>RUF는 radius·ulna·femur의 골화비를 이용한 골성숙도 평가 접근입니다. 이 가이드는 척골 → 요골 → 대퇴골 순서로 영상을 확보하는 교육용 촬영 안내이며 골연령·최종키를 계산하지 않습니다.</p><p>각 부위 3장, 총 9장은 요청에 맞춘 촬영 구성입니다. 서로 다른 세 단면을 의무적으로 찍는 국제 표준을 뜻하지 않습니다. 본 안내에서는 표준 단면을 다시 맞춰 얻은 반복 영상 3장으로 구성했습니다.</p><p>좌측 촬영을 사용한 연구를 참고했습니다. 추적 촬영에서는 부위·측·단면을 일치시키고, 기관의 검증된 촬영 절차가 있으면 그 절차를 우선합니다. 요골 단면은 문헌 간 sagittal/coronal 표기에 차이가 있어 본문은 관상면을 사용한 최근 연구의 자세 설명과 실제 사진을 함께 제시합니다.</p><ul><li><a href="https://pubmed.ncbi.nlm.nih.gov/32402669/" target="_blank" rel="noopener noreferrer">Wan 등, 2020 · RUF 골화비 연구 ↗</a></li><li><a href="https://doi.org/10.1148/radiol.2021204353" target="_blank" rel="noopener noreferrer">2021 · US 골연령 평가법 검증 연구 ↗</a></li><li><a href="https://doi.org/10.2174/0118744400367931250212094541" target="_blank" rel="noopener noreferrer">Hameed 등, 2025 · 실제 탐촉자 배치 Fig. 1 ↗</a> · CC BY 4.0, A–C 사진 패널 발췌</li><li><a href="https://doi.org/10.21037/qims-2025-2009" target="_blank" rel="noopener noreferrer">2026 · 원위 요골·척골·대퇴골 촬영 자세와 OR 영상 ↗</a> · Fig. 2 원본 전체, <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC-ND 4.0</a></li></ul><p class="small muted">골화중심과 골단을 보여 주는 영상은 발달 단계에 따라 모습이 다릅니다. 예시 사진 한 장과 닮았다는 이유로 특정 골연령·성장 종료를 판정하지 않습니다.</p></div></details>`}
function rufReady(){return `<section class="ruf-ready"><div class="eyebrow">BEFORE READING</div><h2>9장을 정리한 뒤, 판독으로</h2><p>같은 검사일·같은 쪽의 영상을 척골 3장, 요골 3장, 대퇴골 3장으로 구분합니다. 파일 이름은 환자 이름 대신 검사 식별코드와 부위·측·번호를 사용하세요.</p><div class="file-groups">${RUF.map(r=>`<div><b>${r.name}</b>${[1,2,3].map(n=>`<code>검사코드_L_${r.prefix}0${n}.jpg</code>`).join('')}</div>`).join('')}</div>${growthLink()}<p class="small muted">Growth AI에서는 의료진 계정으로 로그인해 사진을 직접 입력합니다. 이 버튼은 사이트를 새 탭에서 열며 사진이나 개인정보를 자동 전송하지 않습니다. AI 결과는 의료진 검토용 초안입니다.</p></section>`}
function rufOverview(){return `${intro('RUF · IMAGE ACQUISITION','성장판 초음파 · 9장 촬영 가이드','판독 전에, 비교 가능한 영상을 확보합니다. 척골 원위부 3장 → 요골 원위부 3장 → 대퇴골 원위부 3장.')}${rufRail()}<div class="ruf-count"><b>3부위</b><span>×</span><b>각 3장</b><span>=</span><strong>총 9장</strong></div><div class="callout"><b>성장판의 검은 틈만 찍지 않습니다.</b><p>RUF 평가에는 골단과 그 안의 골화중심을 확인할 수 있는 단면이 필요합니다. 저에코 연골 부분과 밝은 골피질·골화중심의 경계를 함께 담으세요.</p></div><div class="ruf-site-grid">${RUF.map((r,i)=>`<article class="card">${pic('ruf-'+r.id+'-position.jpg','0'+(i+1)+' · 촬영 위치')}<h3>${r.name}</h3><p>${r.ref}</p><a class="button primary" href="#ruf/${i+1}">${r.short} 촬영법 보기 →</a></article>`).join('')}</div><section class="card"><h2>촬영 전 준비</h2><div class="ruf-prep"><div><b>설명과 자세</b><p>아동과 보호자에게 검사를 설명하고 편안한 자세를 잡습니다. 부위·좌우·검사일을 먼저 확인합니다.</p></div><div><b>장비와 방향</b><p>고주파 선형 탐촉자와 B-mode를 사용합니다. 기관의 방향 규칙에 맞춰 표시자를 정하고, 뼈 길이 방향과 화면 방향을 일치시킵니다.</p></div><div><b>화면 최적화</b><p>골단 전체가 들어오는 깊이·화각을 확보하고 표적 높이에 초점을 맞춥니다. 압박·게인 때문에 연골 경계가 사라지지 않게 합니다.</p></div><div><b>같은 단면 3회</b><p>같은 정지 화면을 복사하지 않습니다. 각 부위에서 탐촉자를 다시 맞춘 뒤 표준 단면을 확보하여 3장을 저장합니다.</p></div></div></section><div class="section-heading"><h2>표적 구조가 보이는 실제 초음파</h2></div>${pic('ruf-ossification-reference.jpg','A 요골 · B 척골 · C 대퇴골')}<p class="image-note">저에코 연골성 골단과 골화중심의 범위를 함께 보세요. 원문 측정선은 구조를 이해하기 위한 참고이며, 이 화면은 골화비나 골연령을 계산하지 않습니다.</p>${rufReady()}${rufSources()}`}
function rufStep(i){const r=RUF[i];return `<div class="breadcrumb"><a href="#ruf">성장판 RUF 촬영</a> / ${i+1}단계</div>${intro('RUF · ACQUISITION 0'+(i+1),r.name+' · 3장 촬영',r.ref)}${rufRail(i)}<div class="visual-grid ruf-position-grid">${pic('ruf-'+r.id+'-position.jpg','환자 자세 · 실제 탐촉자')}<section class="ruf-position-text"><span class="eyebrow">POSITION → LANDMARK → PROBE</span><h3>① 환자 자세</h3><p>${r.position}</p><h3>② 먼저 찾을 기준점</h3><p>${r.landmark}</p><h3>③ 탐촉자를 대는 방향</h3><p>${r.probe}</p></section></div><div class="scan-instruction"><span>TARGET</span><p>${r.find}</p></div><div class="ruf-save-flow"><article><span>01</span><h3>표준 단면 확보</h3><p>골단 전체와 골화중심의 경계를 확인하고 첫 영상을 저장합니다.</p><code>${r.prefix}01</code></article><article><span>02</span><h3>다시 맞춰 촬영</h3><p>탐촉자 위치·각도를 다시 잡아 같은 표준 단면을 얻고 저장합니다.</p><code>${r.prefix}02</code></article><article><span>03</span><h3>경계 재확인</h3><p>움직임·비스듬한 단면·경계 잘림 여부를 확인해 세 번째 영상을 저장합니다.</p><code>${r.prefix}03</code></article></div><div class="pitfall"><span>!</span><div><b>촬영할 때 놓치기 쉬운 점</b><p>${r.pitfall}</p></div></div><details><summary>대응 초음파 참고 영상 · ${r.panel} 패널을 확인하세요</summary><div class="details-body">${pic('ruf-ossification-reference.jpg','A 요골 · B 척골 · C 대퇴골')}<p class="small">이 단계는 ${r.panel} 패널입니다. 동일 환자·동일 나이의 영상으로 가정하지 마세요.</p></div></details><section class="card"><h2>저장 전 확인</h2><ul class="ruf-quality"><li><b>부위·좌우</b><span>${r.name}과 촬영 측이 정확히 표시되어 있나요?</span></li><li><b>화각</b><span>골단 전체 윤곽과 인접 골피질이 잘리지 않았나요?</span></li><li><b>단면</b><span>비스듬한 절단으로 골화중심이 작아 보이지 않나요?</span></li><li><b>선명도</b><span>움직임·과도한 압박·게인 때문에 경계가 사라지지 않았나요?</span></li><li><b>3장 구분</b><span>${r.prefix}01·${r.prefix}02·${r.prefix}03은 다시 확보한 영상인가요?</span></li></ul><p class="small muted">경계가 분명하지 않으면 재촬영하거나 판독 제한을 기록합니다. 보이지 않는 구조를 정상·성장 종료로 자동 처리하지 않습니다.</p></section><div class="ruf-next">${i>0?`<a class="button" href="#ruf/${i}">← ${RUF[i-1].short} 촬영</a>`:'<a class="button" href="#ruf">촬영 개요</a>'}${i<2?`<a class="button primary" href="#ruf/${i+2}">다음 · ${RUF[i+1].name} 3장 →</a>`:growthLink()}</div>${i===2?rufReady():''}${rufSources()}`}
const priorClinicalNav=nav;nav=function(){priorClinicalNav();$('#nav').insertAdjacentHTML('beforeend',`<div class="nav-label">GROWTH ULTRASOUND</div><a class="nav-link ${route.startsWith('ruf')?'active':''}" href="#ruf" ${route.startsWith('ruf')?'aria-current="page"':''}><span class="num">RUF</span>성장판 · 9장 촬영</a><a class="nav-link" href="${GROWTH_URL}" target="_blank" rel="noopener noreferrer"><span class="num">↗</span>Growth AI 판독보조</a>`)};
const priorClinicalRender=render;window.removeEventListener('hashchange',render);
render=function(){if(clinicalDialog.open)clinicalDialog.close();let raw=location.hash.slice(1)||'home';let [id,part]=raw.split('/');if(id==='ruf'){route=raw;let i=Number(part)-1;let content=Number.isInteger(i)&&i>=0&&i<3?rufStep(i):rufOverview();$('#main').innerHTML=`<a class="start-primary" href="#ruf/1"><span class="start-copy"><small>RUF · 척골 → 요골 → 대퇴골</small><strong>1단계 시작 <span aria-hidden="true">→</span></strong><span>척골 원위부 3장부터, 총 9장을 순서대로 촬영합니다.</span></span><span class="start-badge" aria-hidden="true">01</span></a>`+content+footer();nav();$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');document.title='RUF 성장판 촬영 · MPS 초음파 진료가이드';window.scrollTo(0,0);return}priorClinicalRender();if(P[id]){let i=Number(part)-1,flowEl=$('#main .scan-flow');if(Number.isInteger(i)&&i>=0&&i<5)flowEl?.insertAdjacentHTML('afterend',diseaseButtons(id,i));else flowEl?.insertAdjacentHTML('afterend',`<details class="region-diseases"><summary>이 부위의 질환 정의·증상 알아보기</summary><div class="details-body">${P[id].steps.map((s,j)=>`<h3>${j+1}. ${e(s.education.name)}</h3>${diseaseButtons(id,j)}`).join('')}</div>`)}if(id==='home')$('#main .stats')?.insertAdjacentHTML('afterend',`<a href="#ruf" class="ruf-home-link"><span><small>NEW · GROWTH ULTRASOUND</small><b>성장판 초음파, 어디에 대고 어떻게 찍을까요?</b><em>척골 3장 · 요골 3장 · 대퇴골 3장</em></span><strong>RUF 촬영 가이드 →</strong></a>`);if(id==='sources')$('#main footer')?.insertAdjacentHTML('beforebegin',`<section class="card"><h2>질환 정의·증상 · 보완 근거</h2><p>원문의 관찰 항목과 연결되는 60개 설명 카드를 추가했습니다. 각 모달의 출처와 증상·영상의 한계를 함께 확인하세요.</p>${Object.values(CLINICAL_SOURCES).map(s=>`<div class="source-links"><a href="${s[1]}" target="_blank" rel="noopener noreferrer">${e(s[0])} ↗</a></div>`).join('')}${rufSources()}</section>`)};
window.addEventListener('hashchange',render);
document.addEventListener('click',ev=>{let b=ev.target.closest('[data-condition]');if(b){let [id,i,j]=b.dataset.condition.split('/');showCondition(id,+i,+j)}if(ev.target.closest('[data-clinical-close]'))clinicalDialog.close()});
// Include the new clinical keywords in the existing search without changing legacy results.
const priorClinicalSearch=searchView;searchView=function(q){let out=priorClinicalSearch(q),needle=q.trim().toLocaleLowerCase(),matches=[];if(!needle)return out;ids.forEach(id=>CONDITIONS[id].forEach((row,i)=>row.conditions.forEach((c,j)=>{if([c.name,c.definition,c.symptoms].join(' ').toLocaleLowerCase().includes(needle))matches.push([id,i,j,c])})));if(matches.length)out+=`<div class="section-heading"><h2>질환 정의·증상</h2><small>${matches.length}건</small></div><div class="disease-buttons">${matches.map(([id,i,j,c])=>`<button data-condition="${id}/${i}/${j}"><span>${e(c.name)}</span><small>${names[id]} · ${i+1}단계 ＋</small></button>`).join('')}</div>`;if(/ruf|성장|골화|골연령/i.test(q))out+='<a class="button primary" href="#ruf">RUF 성장판 촬영 가이드 →</a>';return out};
render();
function rufPrint(){
 $('#print-root').innerHTML=`<div class="print-page">${rufOverview()}</div>`+RUF.map((_,i)=>`<section class="print-page">${rufStep(i)}</section>`).join('');
 $('#print-root').querySelectorAll('details').forEach(d=>d.open=true);
 $('#print-root').querySelectorAll('img').forEach(img=>img.loading='eager');
 window.print();
}
const priorClinicalPrint=printContent;
printContent=function(kind,id){if(kind==='guide'&&route.startsWith('ruf')&&!id){rufPrint();return}const nativePrint=window.print;if(kind==='guide'){window.print=function(){const selected=id?[id]:ids;$('#print-root').insertAdjacentHTML('beforeend',`<section class="print-page"><h1>질환 정의·증상 참고</h1>${selected.map(k=>`<h2>${names[k]}</h2>${CONDITIONS[k].map((row,i)=>`<h3>${i+1}. ${e(P[k].steps[i].education.name)}</h3>${row.conditions.map(c=>`<article class="print-condition"><h4>${e(c.name)}</h4><p><b>정의</b> ${e(c.definition)}</p><p><b>증상</b> ${e(c.symptoms.replaceAll(';',' · '))}</p><p><b>영상과 연결</b> ${e(c.link)}</p><small>출처: ${e(CLINICAL_SOURCES[c.source][0])} · ${e(CLINICAL_SOURCES[c.source][1])}</small></article>`).join('')}`).join('')}`).join('')}</section>${!id?`<section class="print-page">${rufOverview()}</section>${RUF.map((_,i)=>`<section class="print-page">${rufStep(i)}</section>`).join('')}`:''}`);$('#print-root').querySelectorAll('img').forEach(img=>img.loading='eager');nativePrint.call(window)}}try{priorClinicalPrint(kind,id)}finally{window.print=nativePrint}};
