/* MPS EMR integration. Original protocol and original images are retained. */
const guideCopyright='Copyright 2026  HAEON CLINIC. All rights reserved.';
const guideOriginalFooter=footer;
footer=function(){return `<footer class="emr-guide-footer"><details><summary>원본 제작·출처 안내</summary>${guideOriginalFooter()}</details>${GUIDE_DISCLAIMER}<p class="copyright">${guideCopyright}</p></footer>`};
function teachingFor(key){return TEACHING.images[key]||{kind:'원문 참고',laterality:'좌우 미표기 · 원문에서 촬영 측을 확인하세요.',orientation:'화면의 좌우와 환자의 좌우는 다릅니다.',why:'원본 페이지에 포함된 그림은 각 검사 단계의 한국어 설명과 함께 확인하세요.'}}
function imageGlossary(key){const t=teachingFor(key),m=mediaInfo(key);let dict=t.region?TEACHING.glossary[t.region]:Object.assign({},...Object.values(TEACHING.glossary).map(x=>Object.fromEntries(Object.entries(x).filter(([k])=>k.length>2))));
 const text=[m.caption,m.title,t.why,t.orientation].join(' ');let textPage='';
 let page=key.match(/^(shoulder|elbow|wrist|hip|knee|ankle)-p(\d+)-/);if(page){const doc=V.docs.find(x=>x.id===page[1]);if(doc)textPage=doc.pages[+page[2]-1]?.text||'';else textPage=''}else textPage='';
 const all=Object.entries(dict),forced=(t.labelKeys||[]).filter(k=>dict[k]).map(k=>[k,dict[k]]),hits=[...forced,...all.filter(([k])=>k.length>1&&!forced.some(([x])=>x===k)).filter(([k])=>new RegExp('(^|[^A-Za-z])'+k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?=$|[^A-Za-z])','i').test(text+' '+textPage))];
 return `<div class="anatomy-legend"><b>그림 읽기 · 한글 해부학 약어</b><div class="legend-chips">${hits.slice(0,9).map(([k,v])=>`<span>${e(k)}(${e(v)})</span>`).join('')||'<span>화살표·별표의 뜻은 아래 원문 그림 설명을 확인하세요.</span>'}</div><details><summary>${t.region?'이 부위':'공통'} 약어 전체 보기</summary><div class="legend-chips">${all.map(([k,v])=>`<span>${e(k)}(${e(v)})</span>`).join('')}</div><small>A·B·C 등 패널 번호와 같은 글자의 해부 표기는 문맥으로 구분합니다.</small></details></div>`;
}
function imageTeaching(key,full=false){const t=teachingFor(key);return `<div class="image-teaching"><div class="side-label"><span>촬영 측</span>${e(t.laterality)}</div><h4>${t.kind==='정상 참고'?'왜 정상 참고 영상인가요?':t.kind.includes('병리')?'어떤 점이 병리 소견인가요?':'어디를 보는 사진인가요?'}</h4><p>${e(t.why)}</p>${full?`<div class="orientation"><b>화면 방향 · 패널 읽기</b><p>${e(t.orientation)}</p></div>`:''}${imageGlossary(key)}${full&&t.pitfall?`<div class="reading-limit"><b>함께 확인할 점</b><p>${e(t.pitfall)}</p></div>`:''}</div>`}
pic=function(key,label='',tone=''){const m=mediaInfo(key);return `<figure class="visual-card ${tone}"><div class="visual-label"><span>${label||m.kind||'참고 영상'}</span><small>확대 · 해설 ↗</small></div><button class="image-open" data-photo="${e(key)}" aria-label="${e(m.title)} 확대"><img src="${e(DATA.assets[key])}" alt="${e(m.title)} · ${e(teachingFor(key).laterality)}" loading="lazy"></button><figcaption><b>${e(m.title)}</b>${imageTeaching(key)}<small class="photo-source">${e(m.source)}</small></figcaption></figure>`};
comparePhotos=function(id,i){const s=V.steps[id][i],extra=s.pathologyExtra||[];return `<div class="section-heading comparison-heading"><h2>정상에서 출발해, 병리의 차이를 읽습니다</h2><small>정상 참고 1 · 병리·감별 ${1+extra.length}</small></div><div class="visual-grid comparison-photos">${pic(s.normal,'NORMAL · 정상 참고','normal-image')}${pic(s.pathology,'CASE 01 · 병리 사례','path-image')}${extra.map((k,j)=>pic(k,`CASE ${String(j+2).padStart(2,'0')} · 병리·감별`,'path-image')).join('')}</div><p class="image-note">각 그림은 독립된 교육 자료이며 같은 환자·같은 구조의 전후 비교가 아닐 수 있습니다. 그림 안의 정상 비교 패널과 자기공명·방사선·컴퓨터단층영상은 해설에서 구분합니다.${!extra.length?' 이 단계는 확인된 병리 그림 1개를 수록했습니다.':''}</p>`};
const sourceShowImage=showImage;
showImage=function(src,title,body){const key=Object.keys(DATA.assets).find(k=>DATA.assets[k]===src);sourceShowImage(src,title,`${key?imageTeaching(key,true):''}<details class="image-credit"><summary>원문 설명 · 출처 · 이용조건</summary>${body}</details><p class="dialog-note">의료진 교육 참고 자료 · 영상만으로 개별 환자의 진단·치료를 결정하지 않습니다.</p><p class="copyright">${guideCopyright}</p>`)};
const integratedHome=home;
home=function(){return `<section class="emr-intro"><span class="eyebrow">CLINICAL REFERENCE · 06</span><h1>MPS 초음파가이드</h1><p>정상 구조를 찾고, 병리의 차이를 이해하고, 관찰을 기록합니다.</p><div class="intro-meta"><span>6개 부위</span><span>30개 검사 단계</span><span>정상·병리 해설</span><span>원문 PDF 89쪽</span></div></section><div class="chapter-grid emr-chapters">${ids.map((id,i)=>`<a class="chapter-card" href="#${id}/1"><div><small>0${i+1} · ${english[id]}</small><h3>${names[id]} <span>↗</span></h3><p>${P[id].steps.map(s=>s.education.name.split('·')[0].trim()).join(' · ')}</p><span class="chapter-foot">5단계 검사 가이드 →</span></div></a>`).join('')}</div><section class="reading-workflow"><div><span>01</span><b>위치와 자세</b><p>탐촉자와 해부 기준점 확인</p></div><div><span>02</span><b>정상과 병리</b><p>사진별 근거·한글 약어·촬영 측</p></div><div><span>03</span><b>관찰 기록</b><p>확인한 소견을 작성·복사·인쇄</p></div></section><div class="learning-path"><b>빠른 열람</b><a href="#atlas">정상·병리 아틀라스 →</a><a href="#pdf">원문 PDF →</a><a href="#basics">초음파 기본기 →</a><a href="#report">관찰 기록 →</a></div><details><summary>원본 포털 소개 · 학습 자료 전체 보기</summary><div class="details-body">${integratedHome()}</div></details>`};
// Keep every original hash route and clinical definition event handler.
const emrRender=render;
render=function(){emrRender();document.title='MPS 초음파가이드 · MPS EMR';document.querySelector('.start-primary')?.remove();document.querySelectorAll('.setup-grid .image-teaching').forEach(el=>{el.querySelector('h4')?.remove();el.querySelector('h4 + p')?.remove()});};
window.removeEventListener('hashchange',emrRender);window.addEventListener('hashchange',render);
window.addEventListener('beforeprint',()=>{const root=document.querySelector('#print-root');if(root?.innerHTML&&!root.querySelector('.guide-disclaimer'))root.insertAdjacentHTML('beforeend',GUIDE_DISCLAIMER+`<p class="copyright">${guideCopyright}</p>`)});
render();
