/* Visual edition: original educational content and records are retained. */
const V=DATA.visual, oldHome=home,oldRegion=region,oldStep=step,oldAtlas=atlas,oldSources=sources,oldRender=render,oldNav=nav;

function mediaInfo(key){return V.media[key]||{title:'손목터널증후군 · 정중신경 팽대와 편평화',source:'Meyer et al. 2018 · Fig. 8',url:R.cts2[1]+'#F8',license:'CC BY 4.0',kind:'공개 논문'}}
function pic(key,label='',tone=''){const m=mediaInfo(key);return `<figure class="visual-card ${tone}"><div class="visual-label"><span>${label||m.kind}</span><small>클릭하여 확대 ⤢</small></div><button class="image-open" data-photo="${e(key)}" aria-label="${e(m.title)} 확대"><img src="${DATA.assets[key]}" alt="${e(m.title)}" loading="lazy"></button><figcaption><b>${e(m.title)}</b><small>${e(m.source)}</small></figcaption></figure>`}
function flow(id,idx=-1){return `<div class="scan-flow">${P[id].steps.map((s,i)=>`<a href="#${id}/${i+1}" class="${i===idx?'selected':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${s.education.name}</b></a>`).join('')}</div>`}
function comparePhotos(id,i){const s=V.steps[id][i];return `<div class="visual-grid comparison-photos">${pic(s.normal,'03 · 정상 해부','normal-image')}${pic(s.pathology,s.unpaired?'04 · 내전근 해부 보충':'04 · 병리 사례','path-image')}</div><p class="image-note">${s.unpaired?'이 단계에는 검증한 내전근 병리 사진을 아직 수록하지 않았습니다. 정상 영상을 병리로 표시하지 않으며 아래 해설로 손상 소견을 학습합니다.':'두 영상은 독립된 교육 사례입니다. 같은 환자·같은 단면의 전후 사진이 아닐 수 있습니다. 복합 그림에는 MRI·도식·도플러가 함께 포함될 수 있습니다.'}</p>`}
function stepVisual(id,i){const s=V.steps[id][i],d=P[id].steps[i].education;return `<section class="visual-lesson"><div class="section-heading"><h2>몸 위의 위치를, 화면 속 구조로</h2><a href="#pdf/${id==='hand_wrist'?'wrist':id}">ESSR 전체 PDF →</a></div><div class="visual-grid setup-grid">${pic(s.position,'01 · 환자 자세와 탐촉자')}${pic(s.anatomy,'02 · 관련 해부 참고')}</div><div class="scan-instruction"><span>SCAN</span><p>${d.technique}</p></div>${comparePhotos(id,i)}<div class="signal-grid"><div><span class="signal green-dot"></span><b>정상에서 찾을 것</b><p>${d.normal}</p></div><div><span class="signal red-dot"></span><b>이상을 의심하는 변화</b><p>${d.abnormal}</p></div></div><div class="pitfall"><span>!</span><div><b>놓치기 쉬운 판독 함정</b><p>${d.pitfall}</p></div></div>${s.extra.length?`<div class="section-heading"><h2>탐촉자 배치·추가 단면</h2><small>실제 검사 사진과 대응 영상</small></div><div class="visual-grid">${s.extra.map(k=>pic(k)).join('')}</div>`:''}<div class="decision-flow"><div><b>① 기준점 찾기</b><small>뼈 → 표적 구조</small></div><span>→</span><div><b>② 두 면 확인</b><small>장축 ↔ 단축</small></div><span>→</span><div><b>③ 변화 재확인</b><small>각도·압박·움직임</small></div><span>→</span><div><b>④ 증상과 연결</b><small>기록·추가 평가</small></div></div></section>`}
home=function(){const legacy=oldHome();return `<section class="visual-hero"><div><div class="eyebrow">MPS · VISUAL ULTRASOUND ATLAS</div><h1>사진으로 익히고,<br><em>차이를 읽는</em><br>초음파.</h1><p>환자 자세부터 탐촉자, 정상 해부와 병리까지.<br>한의사·한의대생을 위한 실전 교육 포털.</p><div class="actions"><a class="button" href="#pdf">첨부 PDF 전체 보기</a></div></div><div>${pic(V.hero,'검사자 · 환자 · 탐촉자')}<small class="image-note">반월상연골 돌출 평가 연구의 자세 예시. 모든 무릎 검사의 공통 자세를 뜻하지 않습니다.</small></div></section><div class="stats"><div class="stat"><b>06</b><small>부위별 프로토콜</small></div><div class="stat"><b>30</b><small>보존된 검사 단계</small></div><div class="stat"><b>90</b><small>원문 확인 항목</small></div><div class="stat"><b>89</b><small>첨부 PDF 전체 페이지</small></div></div><div class="section-heading"><h2>어디부터 살펴볼까요?</h2><small>원본 통합 파일의 순서 그대로</small></div><div class="chapter-grid">${ids.map((id,i)=>`<a class="chapter-card" href="#${id}"><img src="${DATA.assets[V.steps[id][0].position]}" alt="${names[id]} 검사 자세"><div><small>PROTOCOL 0${i+1} · 5 STEPS</small><h3>${names[id]} <span>↗</span></h3><p>${P[id].description}</p></div></a>`).join('')}</div><div class="learning-path"><b>처음 배우는 분께</b><a href="#basics">기본기 익히기 →</a><a href="#atlas">정상·병리 사진 비교 →</a><a href="#cases">판독 연습 →</a><a href="#report">관찰 기록 →</a></div><details><summary>기존 포털 소개·학습 질문 전체 보기</summary><div class="details-body">${legacy}</div></details>`};
region=function(id){return `${intro(english[id]+' · VISUAL PROTOCOL',names[id]+' 초음파',P[id].description)}${flow(id)}<div class="section-heading"><h2>5개 검사 영역 · 사진으로 들어가기</h2></div><div class="chapter-grid">${P[id].steps.map((s,i)=>`<a class="chapter-card" href="#${id}/${i+1}"><img src="${DATA.assets[V.steps[id][i].normal]}" alt="${e(s.education.name)} 정상 해부"><div><small>STEP 0${i+1}</small><h3>${s.education.name}</h3><p>${s.education.intro}</p></div></a>`).join('')}</div><div class="actions"><a class="button" href="#pdf/${id==='hand_wrist'?'wrist':id}">ESSR 원문 전체</a><button data-action="print-region" data-region="${id}">이 부위 인쇄</button></div><details><summary>기존 부위 소개·원문 순서 전체 보기</summary><div class="details-body">${oldRegion(id)}</div></details>`};
step=function(id,i){let legacy=oldStep(id,i),marker='<div class="section-heading"><h2>관찰 기록 연습';let tail=legacy.slice(legacy.indexOf(marker));const d=P[id].steps[i].education;return `<div class="breadcrumb"><a href="#home">교육 포털</a> / <a href="#${id}">${names[id]}</a> / ${i+1}단계</div>${intro(english[id]+' · STEP 0'+(i+1),d.name,d.intro)}${flow(id,i)}${stepVisual(id,i)}<details><summary>전문 해설 · 검사법·소견·기록 자세히 읽기</summary><div class="details-body">${educationalBody(id,i)}</div></details><details><summary>추가 정상·병리 사진 인터넷 검색</summary><div class="details-body actions"><a class="button" target="_blank" rel="noopener" href="https://www.google.com/search?tbm=isch&q=${encodeURIComponent(d.query+' normal')}">정상 이미지 검색 ↗</a><a class="button" target="_blank" rel="noopener" href="https://www.google.com/search?tbm=isch&q=${encodeURIComponent(d.query+' pathology')}">병리 이미지 검색 ↗</a></div></details>${tail}`};
atlas=function(id){let list=P[id]?[id]:ids;return `${intro('VISUAL LIBRARY','정상·병리 이미지 아틀라스','사진을 클릭하면 확대 영상·출처·원문 설명을 확인할 수 있습니다.')}<div class="actions">${ids.map(k=>`<a class="button" href="#atlas/${k}">${names[k]}</a>`).join('')}</div>${list.map(k=>`<section><div class="section-heading"><h2>${names[k]}</h2></div>${P[k].steps.map((s,i)=>`<h3><a href="#${k}/${i+1}">${i+1}. ${s.education.name} →</a></h3>${comparePhotos(k,i)}`).join('')}</section>`).join('')}<details><summary>이전 사진 자료실·검색 링크 모두 보기</summary><div class="details-body">${oldAtlas(id)}</div></details>`};
function pdfLibrary(id){let doc=V.docs.find(d=>d.id===id);return `${intro('ESSR · COMPLETE PDF LIBRARY','첨부 PDF 전체 열람','7개 파일의 89쪽을 모두 수록했습니다. 표지와 텍스트 전용 페이지도 삭제하지 않았습니다. PDF 그림은 해당 검사 단계에도 연결됩니다.')}<div class="actions">${V.docs.map(d=>`<a class="button ${d.id===id?'primary':''}" href="#pdf/${d.id}">${d.id==='combined'?'통합 가이드':names[d.id==='wrist'?'hand_wrist':d.id]} · ${d.pages.length}쪽</a>`).join('')}</div>${doc?`<div class="section-heading"><h2>${doc.file}</h2><a href="originals/${encodeURIComponent(doc.file)}" download>원본 PDF 다운로드 ↗</a></div><p class="small muted">원본 다운로드는 전체 폴더에서 작동합니다. 아래 페이지는 단일 HTML에도 내장되어 있습니다.</p><div class="pdf-grid">${doc.pages.map((p,i)=>`<article class="pdf-page"><button class="image-open" data-pdf="${doc.id}/${i}" aria-label="${i+1}쪽 확대"><img src="${DATA.assets[p.file]}" alt="${e(doc.file)} ${i+1}쪽" loading="lazy"></button><b>${i+1} / ${doc.pages.length}쪽</b><details><summary>원문 텍스트 펼치기</summary><pre>${e(p.text)}</pre></details></article>`).join('')}</div>`:`<div class="callout"><b>검사 그림 → 대응 초음파 → 원문 설명</b><p>부위 이름을 눌러 첨부 PDF 전체를 펼치세요. 영어 원문을 보존했고, 한국어 설명은 각 단계의 사진·해설에서 함께 읽을 수 있습니다.</p></div>`}`}
sources=function(){return oldSources()+`<section class="card"><h2>시각 자료 확장판 · 출처와 사용 범위</h2><p>위의 ‘직접 포함한 사진 4개’는 이전 편집본의 기록입니다. 이번 판은 ESSR PDF 89쪽, PDF에서 발췌한 검사 자세·정상 영상, 공개 논문 그림, Dropbox 해부 그림을 추가했습니다. 아래 목록과 사진 확대 창에 개별 출처를 표시합니다.</p><p>공개 논문 그림은 원본 전체를 보존했습니다. CC BY-NC / ND 자료는 비상업적 교육 범위·변경 금지 조건을 따릅니다. 사용자 제공 자료의 원저작자 표기도 유지했습니다. 한국어 제목·교육 해설은 별도 작성했습니다.</p>${Object.entries(V.media).map(([k,m])=>`<details><summary>${e(m.title)} · ${e(m.kind)}</summary><div class="details-body"><p>${e(m.source)}</p><p class="small">${e(m.license)}</p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">출처 원문 ↗</a>`:''}</div></details>`).join('')}</section>`};
nav=function(){oldNav();$('#nav').insertAdjacentHTML('beforeend','<a class="nav-link" href="#pdf"><span class="num">▧</span>첨부 PDF 전체 · 89쪽</a>')};
// The original hash listener dispatches through original render; PDF route is added here.
window.removeEventListener('hashchange',oldRender);
function addStartButton(){
 const parts=route.split('/');let id=P[parts[0]]?parts[0]:P[parts[1]]?parts[1]:parts[1]==='wrist'?'hand_wrist':'shoulder';
 const label=names[id];
 $('#main').insertAdjacentHTML('afterbegin',`<a class="start-primary" href="#${id}/1" aria-label="${label} 1단계 시작"><span class="start-copy"><small>${label} · 5단계 검사 가이드</small><strong>1단계 시작 <span aria-hidden="true">→</span></strong><span>환자 자세부터 정상·병리 영상까지, 순서대로 살펴보세요.</span></span><span class="start-badge" aria-hidden="true">01</span></a>`);
}

render=function(){if(location.hash.startsWith('#pdf')){route=location.hash.slice(1);$('#main').innerHTML=pdfLibrary(route.split('/')[1])+footer();nav();$('#sidebar').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');window.scrollTo(0,0)}else oldRender();addStartButton()};
window.addEventListener('hashchange',render);
const lightbox=document.createElement('dialog');lightbox.className='image-dialog';lightbox.setAttribute('aria-label','교육 이미지 확대');document.body.append(lightbox);
function showImage(src,title,body){lightbox.innerHTML=`<div class="dialog-toolbar"><b>${e(title)}</b><button data-v="close">닫기 ✕</button></div><div class="zoom-scroll"><img src="${src}" alt="${e(title)}"></div><div class="dialog-caption">${body}</div>`;lightbox.showModal()}
document.addEventListener('click',ev=>{let photo=ev.target.closest('[data-photo]'),page=ev.target.closest('[data-pdf]'),b=ev.target.closest('[data-v]');if(photo){let k=photo.dataset.photo,m=mediaInfo(k);showImage(DATA.assets[k],m.title,`<p>${e(m.source)}</p><p class="small">${e(m.license)}</p>${m.url?`<a href="${m.url}" target="_blank" rel="noopener">원문 출처 ↗</a>`:''}${m.caption?`<details><summary>원문 그림 설명</summary><p>${e(m.caption)}</p></details>`:''}`)}if(page){let [id,n]=page.dataset.pdf.split('/'),d=V.docs.find(x=>x.id===id);showImage(DATA.assets[d.pages[n].file],d.file+' · '+(+n+1)+'쪽','<p>사용자 제공 ESSR PDF · 원본 페이지 전체</p>')}if(!b)return;let a=b.dataset.v;if(a==='close')lightbox.close();});

// Include the same visual cards in generated print guides, followed by full text.
const textEducation=educationalBody;educationalBody=function(id,i){return textEducation(id,i)};
const legacyPrint=printContent;printContent=function(kind,id){const old=educationalBody;if(kind!=='report')educationalBody=(k,i)=>stepVisual(k,i)+textEducation(k,i);try{legacyPrint(kind,id)}finally{educationalBody=old}};
render();
