/* Reference diagrams preserve the existing guide's numbers; no patient scores. */
function GuideVisual({id}){
 const [phase,setPhase]=useState(0);
 const stages=[['Pre-PHV','성장 가속 준비기'],['Stage 1','성장 가속기'],['Stage 2 · PHV','최대 급성장기'],['Stage 3','성장 감속기'],['Stage 4~5','성장 종료 초기 및 임박기']];
 if(id==='m-overview')return <section className="report-visual" aria-label="MGI 기준 구간 시각화"><div className="report-visual-title"><h3>MGI 기준을 한눈에</h3><span>6.0점 척도 · 기준 구간</span></div>{[['주의',0,3.5,'3.5 이하','coral'],['보통',3.6,4.1,'3.6 ~ 4.1',''],['양호',4.2,4.7,'4.2 ~ 4.7','aqua'],['강점',4.8,6,'4.8 이상','blue']].map(([label,start,end,text,tone])=><div className="report-bar-row" key={label}><strong>{label}</strong><div className="report-bar-track"><div className={'report-bar-fill '+tone} style={{marginLeft:(start/6*100)+'%',width:((end-start)/6*100)+'%'}}/></div><span className="report-bar-value">{text}</span></div>)}<div className="report-axis"><span>0</span><span>3</span><span>6점</span></div><p>막대는 본문에 제시된 점수 구간입니다. 특정 선수의 측정 결과를 나타내지 않습니다.</p></section>;
 if(id==='p-phv')return <section className="report-visual" aria-label="PHV 단계별 기존 가중치"><div className="report-visual-title"><h3>성장단계별 가중치</h3><span>기존 MPS 내부 기준</span></div>{[['PHV −2',.9,'성장기 이전'],['PHV −1',1,'성장 가속 시작'],['PHV 0',1.35,'최대 급성장기'],['PHV 1',1.15,'성장 둔화기'],['PHV 2',1,'성장 종료 단계']].map(([label,v,desc])=><div className="report-bar-row" key={label} title={desc}><strong>{label}</strong><div className="report-bar-track"><div className={'report-bar-fill '+(v===1.35?'coral':'blue')} style={{width:(v/1.5*100)+'%'}}/></div><span className="report-bar-value">× {v.toFixed(v===1.35||v===1.15?2:1)}</span></div>)}<div className="report-axis"><span>0</span><span>0.75</span><span>1.5배</span></div><p>기존 가이드의 가중치를 같은 축으로 비교합니다. 가중치는 실제 부상 발생 확률이나 측정된 성장 속도가 아닙니다.</p></section>;
 if(id==='p-hrv-core')return <section className="report-visual" aria-label="SDNN RMSSD 4사분면 기준 도식"><div className="report-visual-title"><h3>두 지표를 함께 읽는 기준 지도</h3><span>수치 축척 없는 설명 도식</span></div><div className="report-chart-layout"><svg viewBox="0 0 380 285" role="img" aria-label="가로 SDNN 50, 세로 RMSSD 40을 기준으로 구분한 네 영역"><rect x="58" y="27" width="145" height="102" rx="10" fill="#fff1e5"/><rect x="207" y="27" width="145" height="102" rx="10" fill="#e0f5ee"/><rect x="58" y="133" width="145" height="102" rx="10" fill="#edf1f6"/><rect x="207" y="133" width="145" height="102" rx="10" fill="#deedff"/><path d="M58 131H352M205 27V235" stroke="#71849b" strokeWidth="1.5" strokeDasharray="4 4"/><g fill="#17395c" textAnchor="middle" fontSize="12" fontWeight="700"><text x="130" y="73">Q3</text><text x="280" y="73">Q1</text><text x="130" y="178">Q4</text><text x="280" y="178">Q2</text></g><g fill="#52677b" textAnchor="middle" fontSize="11"><text x="130" y="94">SDNN ↓ · RMSSD ↑</text><text x="280" y="94">SDNN ↑ · RMSSD ↑</text><text x="130" y="199">SDNN ↓ · RMSSD ↓</text><text x="280" y="199">SDNN ↑ · RMSSD ↓</text><text x="205" y="254">50</text><text x="305" y="273">SDNN (ms) →</text><text x="28" y="135">40</text><text x="91" y="16">RMSSD (ms) ↑</text></g></svg><div className="report-chart-note"><strong>중심 기준</strong><span className="report-number-badge">SDNN 50</span><span className="report-number-badge">RMSSD 40</span><p>SDNN은 심박 간격의 표준편차, RMSSD는 연속 심박 간격 차이의 제곱평균제곱근입니다. 영역별 해석은 아래 본문과 함께 확인합니다.</p><strong style={{marginTop:14}}>높은 값도 맥락 확인</strong><span className="report-number-badge coral">RMSSD ≥ 130</span><span className="report-number-badge coral">SDNN ≥ 131</span><p>기존 내부 기준을 보존한 도식입니다. 수치만으로 회복 상태나 특정 부상 확률을 확정하지 않습니다.</p></div></div></section>;
 if(id==='s-phv')return <section className="report-visual" aria-label="성장단계 탐색"><div className="report-visual-title"><h3>성장단계의 흐름</h3><span>단계를 눌러 확인하세요</span></div><div className="report-stage-selector">{stages.map(([name,label],i)=><button key={name} aria-pressed={phase===i} onClick={()=>setPhase(i)}><b>{name}</b><span>{label}</span></button>)}</div><div className="report-stage-detail" aria-live="polite"><b>{stages[phase][0]}</b> · {stages[phase][1]}<br/>해당 단계의 신체 변화와 설명은 아래 본문에서 확인할 수 있습니다.</div><p>본문의 5단계 분류를 순서대로 배치했습니다. 단계 간 폭은 기간이나 성장량을 뜻하지 않습니다.</p></section>;
 return null;
}

const catalog={M:{name:'멘탈 · 심리',english:'MENTAL',description:'멘탈지수와 심리 기술을 읽고 상담으로 연결합니다.',items:mGuideData,icon:'brain',sample:'2026mental2'},P:{name:'피지컬 · 회복',english:'PHYSICAL',description:'성장단계와 자율신경, 체성분·초음파를 함께 살펴봅니다.',items:pGuideData,icon:'activity',sample:'2026physical'},S:{name:'성장 · 체질',english:'STRUCTURE',description:'성장곡선과 성숙 속도를 비교하고 성장 유형을 이해합니다.',items:sGuideData,icon:'sprout',sample:'2026growth'}};
const allItems=Object.entries(catalog).flatMap(([group,c])=>c.items.map(item=>({...item,group})));
const plain=node=>node==null||typeof node==='boolean'?'':typeof node==='string'||typeof node==='number'?String(node):Array.isArray(node)?node.map(plain).join(' '):plain(node.props?.children);
function App(){
 const initial=allItems.find(x=>x.id===location.hash.slice(1))||allItems[0];
 const [group,setGroup]=useState(initial.group),[selected,setSelected]=useState(initial.id),[query,setQuery]=useState('');const reader=useRef(null);
 const item=selected===precautionData.id?precautionData:allItems.find(x=>x.id===selected)||initial;
 const terms=query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
 const matches=(terms.length?allItems:catalog[group].items).filter(x=>terms.every(term=>(x.title+' '+x.subtitle+' '+plain(x.content)).toLocaleLowerCase().includes(term)));
 function choose(id){const next=allItems.find(x=>x.id===id);if(next)setGroup(next.group);setSelected(id);history.replaceState(null,'','#'+id);reader.current?.scrollTo(0,0);}
 function tab(key){setQuery('');choose(catalog[key].items[0].id);}
 useEffect(()=>{const change=()=>{const found=allItems.find(x=>x.id===location.hash.slice(1));if(found){setGroup(found.group);setSelected(found.id);}};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 const index=catalog[group].items.findIndex(x=>x.id===selected);
 return <div className="guide-app" data-theme={group}>
 <aside className="guide-rail"><a href="../emr.html" className="guide-brand"><img src="../assets/mps-logo-black.png" alt="MPS"/><span>emr</span></a><span className="rail-label">한의원 워크스페이스</span><a href="../emr.html" className="rail-link"><span>01</span>MPS차트</a><div className="rail-divider"/><span className="rail-label">환자 안내</span><a href="../guides/index.html" className="rail-link"><span>04</span>한의원 가이드</a><a href="index.html" className="rail-link active" aria-current="page"><span>05</span>MPS 진료가이드</a><a href="../ultrasound-guide/index.html" className="rail-link"><span>06</span>MPS 초음파가이드</a><div className="rail-bottom"><strong>MPS EMR 2.0</strong><span>기록을 다음 진료로.</span><small>해온한의원</small></div></aside>
 <main className="guide-main"><header className="guide-topbar"><span>환자 안내 <b>/</b> MPS 진료가이드</span><a href="../emr.html">EMR로 돌아가기 <span aria-hidden="true">↗</span></a></header>
 <section className="guide-intro"><div><span className="eyebrow">CLINICAL REFERENCE · 05</span><h1>MPS 진료가이드</h1><p>검사 지표의 이해부터 판독, 한의학적 해석과 환자 상담까지.</p></div><div className="guide-sample-links"><small>리포트 샘플</small><a href="samples/standard/index.html" target="_blank" rel="noopener">스탠다드 · 12페이지 ↗</a><a href={'samples/'+catalog[group].sample+'/index.html'} target="_blank" rel="noopener">{group} 심화 리포트 ↗</a></div></section>
 <nav className="guide-tabs" aria-label="진료가이드 분야">{Object.entries(catalog).map(([key,c])=><button key={key} onClick={()=>tab(key)} aria-pressed={group===key}><span className="tab-letter">{key}</span><span className="tab-copy"><small>{c.english} · {c.items.length}개 가이드</small><strong>{c.name}</strong><span>{c.description}</span></span><Icon name={c.icon} size={28}/></button>)}</nav>
 <div className="guide-workspace"><aside className="guide-index"><div className="index-heading"><strong>{terms.length?'전체 분야 검색':group+' · 판독 목차'}</strong><span>{matches.length}</span></div><label className="guide-search"><Icon name="search" size={16}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="지표·키워드 검색" aria-label="전체 가이드 본문 검색"/></label><nav aria-label="가이드 항목">{matches.map((x,i)=><button key={x.id} aria-current={selected===x.id?'true':undefined} onClick={()=>choose(x.id)}><span className="index-number">{terms.length?x.group:String(i+1).padStart(2,'0')}</span><span><strong>{x.title}</strong><small>{x.subtitle}</small></span><span aria-hidden="true">›</span></button>)}{!matches.length&&<p className="empty-results">검색 결과가 없습니다.<br/>다른 지표나 키워드로 검색해 주세요.</p>}</nav><button className="precautions-link" aria-current={selected===precautionData.id?'true':undefined} onClick={()=>choose(precautionData.id)}><Icon name="shield-alert" size={17}/>의료진 사용 시 주의사항 <span>↗</span></button><p className="index-hint">제목을 선택하면 본문을 바로 확인할 수 있습니다.</p></aside>
 <article className="guide-reader" ref={reader} aria-labelledby="reader-title"><header className="reader-heading"><span className="eyebrow">{selected===precautionData.id?'COMMON REFERENCE':catalog[group].english+' / '+String(index+1).padStart(2,'0')}</span><h2 id="reader-title">{item.title}</h2><p>{item.subtitle}</p></header><div className="reader-content" key={item.id}><GuideVisual key={item.id} id={item.id}/>{item.content}</div>{index>=0&&<nav className="reader-pagination" aria-label="이전 다음 가이드"><button disabled={index===0} onClick={()=>choose(catalog[group].items[index-1].id)}>← 이전 항목</button><span>{index+1} / {catalog[group].items.length}</span><button disabled={index===catalog[group].items.length-1} onClick={()=>choose(catalog[group].items[index+1].id)}>다음 항목 →</button></nav>}</article></div>
 __GUIDE_DISCLAIMER__<footer className="guide-footer">Copyright 2026&nbsp; HAEON CLINIC. All rights reserved.</footer></main></div>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
