const catalog={M:{name:'멘탈 · 심리',english:'MENTAL',description:'멘탈지수와 심리 기술을 읽고 상담으로 연결합니다.',items:mGuideData,icon:'brain',sample:'2026mental2'},P:{name:'피지컬 · 회복',english:'PHYSICAL',description:'성장단계와 자율신경, 체성분·초음파를 함께 살펴봅니다.',items:pGuideData,icon:'activity',sample:'2026physical'},S:{name:'성장 · 체질',english:'STRUCTURE',description:'성장곡선과 성숙 속도를 비교하고 성장 유형을 이해합니다.',items:sGuideData,icon:'sprout',sample:'2026growth'}};
const allItems=Object.entries(catalog).flatMap(([group,c])=>c.items.map(item=>({...item,group})));
const plain=node=>node==null||typeof node==='boolean'?'':typeof node==='string'||typeof node==='number'?String(node):Array.isArray(node)?node.map(plain).join(' '):plain(node.props?.children);
function App(){
 const initial=allItems.find(x=>x.id===location.hash.slice(1))||allItems[0];
 const [group,setGroup]=useState(initial.group),[selected,setSelected]=useState(initial.id),[query,setQuery]=useState('');const reader=useRef(null);
 const item=selected===precautionData.id?precautionData:allItems.find(x=>x.id===selected)||initial;
 const terms=query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
 const matches=(terms.length?allItems:catalog[group].items).filter(x=>terms.every(term=>(x.title+' '+x.subtitle+' '+plain(x.content)).toLocaleLowerCase().includes(term)));
 function choose(id){const next=allItems.find(x=>x.id===id);if(next)setGroup(next.group);setSelected(id);history.replaceState(null,'','#'+id);reader.current?.scrollTo(0,0);}
 function tab(key){setQuery('');choose(catalog[key].items[0].id);}
 useEffect(()=>{const change=()=>{const found=allItems.find(x=>x.id===location.hash.slice(1));if(found){setGroup(found.group);setSelected(found.id);}};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 const index=catalog[group].items.findIndex(x=>x.id===selected);
 return <div className="guide-app" data-theme={group}>
 <aside className="guide-rail"><a href="../emr.html" className="guide-brand"><img src="../assets/mps-logo-black.png" alt="MPS"/><span>emr</span></a><span className="rail-label">한의원 워크스페이스</span><a href="../emr.html" className="rail-link"><span>01</span>환자 · 진료기록</a><div className="rail-divider"/><span className="rail-label">환자 안내</span><a href="../guides/index.html" className="rail-link"><span>04</span>한의원 가이드</a><a href="index.html" className="rail-link active" aria-current="page"><span>05</span>MPS 진료가이드</a><div className="rail-bottom"><strong>MPS EMR 2.0</strong><span>기록을 다음 진료로.</span><small>해온한의원</small></div></aside>
 <main className="guide-main"><header className="guide-topbar"><span>환자 안내 <b>/</b> MPS 진료가이드</span><a href="../emr.html">EMR로 돌아가기 <span aria-hidden="true">↗</span></a></header>
 <section className="guide-intro"><div><span className="eyebrow">CLINICAL REFERENCE · 05</span><h1>MPS 진료가이드</h1><p>검사 지표의 이해부터 판독, 한의학적 해석과 환자 상담까지.</p></div><div className="guide-sample-links"><small>리포트 샘플</small><a href="samples/standard/index.html" target="_blank" rel="noopener">스탠다드 · 12페이지 ↗</a><a href={'samples/'+catalog[group].sample+'/index.html'} target="_blank" rel="noopener">{group} 심화 리포트 ↗</a></div></section>
 <nav className="guide-tabs" aria-label="진료가이드 분야">{Object.entries(catalog).map(([key,c])=><button key={key} onClick={()=>tab(key)} aria-pressed={group===key}><span className="tab-letter">{key}</span><span className="tab-copy"><small>{c.english} · {c.items.length}개 가이드</small><strong>{c.name}</strong><span>{c.description}</span></span><Icon name={c.icon} size={28}/></button>)}</nav>
 <div className="guide-workspace"><aside className="guide-index"><div className="index-heading"><strong>{terms.length?'전체 분야 검색':group+' · 판독 목차'}</strong><span>{matches.length}</span></div><label className="guide-search"><Icon name="search" size={16}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="지표·키워드 검색" aria-label="전체 가이드 본문 검색"/></label><nav aria-label="가이드 항목">{matches.map((x,i)=><button key={x.id} aria-current={selected===x.id?'true':undefined} onClick={()=>choose(x.id)}><span className="index-number">{terms.length?x.group:String(i+1).padStart(2,'0')}</span><span><strong>{x.title}</strong><small>{x.subtitle}</small></span><span aria-hidden="true">›</span></button>)}{!matches.length&&<p className="empty-results">검색 결과가 없습니다.<br/>다른 지표나 키워드로 검색해 주세요.</p>}</nav><button className="precautions-link" aria-current={selected===precautionData.id?'true':undefined} onClick={()=>choose(precautionData.id)}><Icon name="shield-alert" size={17}/>의료진 사용 시 주의사항 <span>↗</span></button><p className="index-hint">제목을 선택하면 본문을 바로 확인할 수 있습니다.</p></aside>
 <article className="guide-reader" ref={reader} aria-labelledby="reader-title"><header className="reader-heading"><span className="eyebrow">{selected===precautionData.id?'COMMON REFERENCE':catalog[group].english+' / '+String(index+1).padStart(2,'0')}</span><h2 id="reader-title">{item.title}</h2><p>{item.subtitle}</p></header><div className="reader-content" key={item.id}>{item.content}</div>{index>=0&&<nav className="reader-pagination" aria-label="이전 다음 가이드"><button disabled={index===0} onClick={()=>choose(catalog[group].items[index-1].id)}>← 이전 항목</button><span>{index+1} / {catalog[group].items.length}</span><button disabled={index===catalog[group].items.length-1} onClick={()=>choose(catalog[group].items[index+1].id)}>다음 항목 →</button></nav>}</article></div>
 __GUIDE_DISCLAIMER__<footer className="guide-footer">Copyright 2026&nbsp; HAEON CLINIC. All rights reserved.</footer></main></div>;
}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
